#!/bin/bash

echo "=========================================="
echo "PPO Training Configuration Comparison"
echo "=========================================="
echo ""

echo "1. DEFAULT CONFIG"
echo "Command: python test_env.py"
echo "- 8 parallel envs"
echo "- 84x84 images"
echo "- 200 step episodes"
echo "- 512 steps × 8 envs = 4096 steps/update"
echo "- Total: 500K timesteps"
echo "- Estimated time: Moderate"
echo ""

echo "2. FAST CONFIG (--preset fast)"
echo "Command: python test_env.py --preset fast"
echo "- 16 parallel envs"
echo "- 64x64 images"
echo "- 100 step episodes"
echo "- 256 steps × 16 envs = 4096 steps/update"
echo "- Total: 500K timesteps"
echo "- Estimated time: ~2-3x FASTER than default"
echo ""

echo "3. HIGH QUALITY CONFIG (--preset high_quality)"
echo "Command: python test_env.py --preset high_quality"
echo "- 8 parallel envs"
echo "- 128x128 images"
echo "- 200 step episodes"
echo "- 512 steps × 8 envs = 4096 steps/update"
echo "- Total: 1M timesteps"
echo "- Estimated time: ~2x SLOWER than default"
echo ""

echo "4. CPU ONLY CONFIG (--preset cpu)"
echo "Command: python test_env.py --preset cpu"
echo "- 8 parallel envs"
echo "- 64x64 images"
echo "- 200 step episodes"
echo "- 32 batch size (CPU optimized)"
echo "- No GPU acceleration"
echo "- Estimated time: Moderate (slower without GPU)"
echo ""

echo "5. MAXIMUM SPEED CONFIG (Custom)"
echo "Command:"
echo "  python test_env.py \\"
echo "    --n_envs 32 \\"
echo "    --camera_height 64 \\"
echo "    --camera_width 64 \\"
echo "    --horizon 100 \\"
echo "    --n_steps 256"
echo "- 32 parallel envs (uses more of your 64 cores!)"
echo "- 64x64 images"
echo "- 100 step episodes"
echo "- 256 steps × 32 envs = 8192 steps/update"
echo "- Total: 500K timesteps"
echo "- Estimated time: ~4-5x FASTER than default"
echo ""

echo "=========================================="
echo "Recommendation Based on Use Case"
echo "=========================================="
echo ""
echo "Quick Experiments & Debugging:"
echo "  → python test_env.py --preset fast"
echo ""
echo "Final Training Run:"
echo "  → python test_env.py --preset high_quality"
echo ""
echo "Maximum Speed (with 64 CPU cores):"
echo "  → python test_env.py --n_envs 32 --camera_height 64 --horizon 100"
echo ""
echo "No GPU Available:"
echo "  → python test_env.py --preset cpu"
echo ""

echo "=========================================="
echo "To view all options: python test_env.py --help"
echo "=========================================="
